#!/bin/zsh

function ntfsmount() {
    sudo mkdir /Volumes/NTFS
    sudo /usr/local/bin/ntfs-3g /dev/disk2s2 /Volumes/NTFS -olocal -oallow_other -o auto_xattr
}

alias usb="ntfsmount"
alias s3='aws --endpoint-url="https://s3-svc-dl.wildberries.ru" s3'
alias kg='kubectl get'
alias kd='kubectl describe'
alias ke='kubectl edit'
alias kgpv='kubectl get pv'
alias ktcluster='export KUBECONFIG=$(find ~/.kube -type f -name "config*" | sort -r | fzf --height 30%)'
alias kpcluster='find ~/.kube -type f -name "config*" | sort -r | fzf --height 30% | xargs -I '"'"'{}'"'"' sed -i -E '"'"'s~export KUBECONFIG.*$~export KUBECONFIG={}~g'"'"' ~/.zshrc && source ~/.zshrc'
alias by='bat --language=yaml --theme="TwoDark" --style=plain --color=always'

alias jctl='java -jar jenkins-cli.jar -noCertificateCheck -s https://asd-ecs-jenkins.isus.emc.com -auth maxim_ferapontov:11145d101e974b073ab5fa0e9178e7fb56'
