#!/bin/zsh

function ntfsmount() {
    sudo mkdir /Volumes/NTFS
    sudo /usr/local/bin/ntfs-3g /dev/disk2s2 /Volumes/NTFS -olocal -oallow_other -o auto_xattr
}

alias usb="ntfsmount"
alias kg='kubectl get'
alias kgy='kubectl get -o yaml'
alias kd='kubectl describe'
alias ke='kubectl edit'
alias kgpv='kubectl get pv'
alias ktc='export KUBECONFIG=$(find ~/.kube -type f -name "config*" | sort -r | fzf --height 30%)'
alias kpc='find ~/.kube -type f -name "config*" | sort -r | fzf --height 30% | xargs -I '"'"'{}'"'"' sed -i -E '"'"'s~export KUBECONFIG.*$~export KUBECONFIG={}~g'"'"' ~/.zshrc && source ~/.zshrc'
alias by='bat --language=yaml --theme="TwoDark" --style=plain --color=always'
alias lg='lazygit'

