source /Users/maxim/.dotfiles/zsh/oh-my-zshrc

# dotfiles & brew lines
fpath=(/usr/local/share/zsh-completions $fpath)
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
PATH="/Users/maxim/go/bin:$PATH"
export GOPRIVATE=git.wildberries.ru
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"
